---
global:
  scrape_native_histograms: true
otlp:
  keep_identifying_resource_attributes: true
  promote_resource_attributes:
    - service.instance.id
    - service.name
    - service.namespace
    - service.version
    - cloud.availability_zone
    - cloud.region
    - container.name
    - deployment.environment
    - deployment.environment.name
    - host.name
storage:
  tsdb:
    out_of_order_time_window: 10m

scrape_configs:
  - job_name: 'agent-service'
    scrape_interval: 5s
    static_configs:
      - targets: ['agent-service:8080']
